context:
  version: "12.0.0"

package:
  name: c8
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/c8/-/c8-${{ version }}.tgz
  sha256: 77e0dbd7761bef0e52569fc62e387c73f1db08d3edba1c440664ef9d6ccff534

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - c8 --help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: "output coverage reports using Node.js' built in coverage"
  homepage: https://github.com/bcoe/c8
  repository: https://github.com/bcoe/c8

extra:
  recipe-maintainers:
    - danielnachun
