context:
  version: "11.0.0"

package:
  name: c8
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/c8/-/c8-${{ version }}.tgz
  sha256: 484a79a9f703699250a60c7c4be134ded5ebd80bf5dd7547beff918811fb0508

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - c8 --help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: "output coverage reports using Node.js' built in coverage"
  homepage: https://github.com/bcoe/c8
  repository: https://github.com/bcoe/c8

extra:
  recipe-maintainers:
    - danielnachun
