context:
  version: 10.1.2

package:
  name: c8
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/c8/-/c8-${{ version }}.tgz
  sha256: 1cc80fe1200ca0f02a208ad48f0d56ec4ba4e6e925a2ef96b88b1e9d1c2beb29

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - c8 --help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: "output coverage reports using Node.js' built in coverage"
  homepage: https://github.com/bcoe/c8
  repository: https://github.com/bcoe/c8

extra:
  recipe-maintainers:
    - danielnachun
